services:


  # --- SMTP TEST SERVER (Mailpit) ---
  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    restart: unless-stopped

  # --- NO CHANGE: DATABASE ---
  db-1:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=kahf
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fred
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
